import type { Metadata } from 'next';
import { IBM_Plex_Mono, Libre_Franklin } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils/cn';


const IBMPlexMono = IBM_Plex_Mono({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-mono',
});

const LibreFranklin = Libre_Franklin({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen bg-background font-sans antialiased', IBMPlexMono.variable, LibreFranklin.variable)}>{children}</body>
    </html>
  );
}
